export const charList = {
    albedo: {
        name: "Albedo",
        vision: "geo",
        icon: "images/portraits/Albedo_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Tusk of Monoceros Caeli",
        weeklyImg: [GenerateTalentImage("images/weekly/tusk of monoceros caeli.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Basalt Pillar",
        bossImg: "images/boss/basalt pillar.png",
        boss: "(Geo Hypostasis)"
    },
    jean: {
        name: "Jean",
        vision: "anemo",
        icon: "images/portraits/Jean_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Plume",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins plume.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Hurricane Seed",
        bossImg: "images/boss/hurricane seed.png",
        boss: "(Anemo Hypostasis)"
    },
    amber: {
        name: "Amber",
        vision: "pyro",
        icon: "images/portraits/Amber_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Dvalin's Sigh",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    barbara: {
        name: "Barbara",
        vision: "hydro",
        icon: "images/portraits/Barbara_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Ring of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/ring of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Cleansing Heart",
        bossImg: "images/boss/cleansing heart.png",
        boss: "(Oceanid)"
    },
    beidou: {
        name: "Beidou",
        vision: "electro",
        icon: "images/portraits/Beidou_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Dvalin's Sigh",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Lightning Prism",
        bossImg: "images/boss/lightning prism.png",
        boss: "(Electro Hypostasis)"
    },
    alhaitham: {
        name: "Alhaitham",
        vision: "dendro",
        icon: "images/portraits/Alhaitham_Icon.png",
        talent: "Ingenuity",
        talentImg: [GenerateTalentImage("images/talents/ingenuity.png")],
        days: "(Tue/Fri)",
        weekly: "Mirror of Mushin",
        weeklyImg: [GenerateTalentImage("images/weekly/mirror of mushin.png")],
        weeklyBoss: "(Everlasting Lord of Arcane Wisdom)",
        bossMat: "Pseudo-Stamens",
        bossImg: "images/boss/pseudo stamen.png",
        boss: "(Setekh Wenut)"
    },
    aloy: {
        name: "Aloy",
        vision: "cryo",
        icon: "images/portraits/Aloy_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Molten Moment",
        weeklyImg: [GenerateTalentImage("images/weekly/molten moment.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Crystalline Bloom",
        bossImg: "images/boss/crystalline bloom.png",
        boss: "(Cryo Hypostasis)"
    },
    chongyun: {
        name: "Chongyun",
        vision: "cryo",
        icon: "images/portraits/Chongyun_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Sigh",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    diona: {
        name: "Diona",
        vision: "cryo",
        icon: "images/portraits/Diona_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Shard of a Foul Legacy",
        weeklyImg: [GenerateTalentImage("images/weekly/shard of a foul legacy.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    kaeya: {
        name: "Kaeya",
        vision: "cryo",
        icon: "images/portraits/Kaeya_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Spirit Locket of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    rosaria: {
        name: "Rosaria",
        vision: "cryo",
        icon: "images/portraits/Rosaria_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Shadow of the Warrior",
        weeklyImg: [GenerateTalentImage("images/weekly/shadow of the warrior.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    ganyu: {
        name: "Ganyu",
        vision: "cryo",
        icon: "images/portraits/Ganyu_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Shadow of the Warrior",
        weeklyImg: [GenerateTalentImage("images/weekly/shadow of the warrior.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    qiqi: {
        name: "Qiqi",
        vision: "cryo",
        icon: "images/portraits/Qiqi_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Tail of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Hoarfrost Core",
        bossImg: "images/boss/hoarfrost core.png",
        boss: "(Cryo Regisvine)"
    },
    eula: {
        name: "Eula",
        vision: "cryo",
        icon: "images/portraits/Eula_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dragon Lord's Crown",
        weeklyImg: [GenerateTalentImage("images/weekly/dragon lords crown.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Crystalline Bloom",
        bossImg: "images/boss/crystalline bloom.png",
        boss: "(Cryo Hypostasis)"
    },
    sucrose: {
        name: "Sucrose",
        vision: "anemo",
        icon: "images/portraits/Sucrose_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Spirit Locket of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/spirit locket of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Hurricane Seed",
        bossImg: "images/boss/hurricane seed.png",
        boss: "(Anemo Hypostasis)"
    },
    venti: {
        name: "Venti",
        vision: "anemo",
        icon: "images/portraits/Venti_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Tail of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/tail of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Hurricane Seed",
        bossImg: "images/boss/hurricane seed.png",
        boss: "(Anemo Hypostasis)"
    },
    keqing: {
        name: "Keqing",
        vision: "electro",
        icon: "images/portraits/Keqing_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Ring of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/ring of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Lightning Prism",
        bossImg: "images/boss/lightning prism.png",
        boss: "(Electro Hypostasis)"
    },
    lisa: {
        name: "Lisa",
        vision: "electro",
        icon: "images/portraits/Lisa_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Dvalin's Claw",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins claw.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Lightning Prism",
        bossImg: "images/boss/lightning prism.png",
        boss: "(Electro Hypostasis)"
    },
    razor: {
        name: "Razor",
        vision: "electro",
        icon: "images/portraits/Razor_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Claw",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins claw.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Lightning Prism",
        bossImg: "images/boss/lightning prism.png",
        boss: "(Electro Hypostasis)"
    },
    fischl: {
        name: "Fischl",
        vision: "electro",
        icon: "images/portraits/Fischl_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Spirit Locket of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/spirit locket of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Lightning Prism",
        bossImg: "images/boss/lightning prism.png",
        boss: "(Electro Hypostasis)"
    },
    noelle: {
        name: "Noelle",
        vision: "geo",
        icon: "images/portraits/Noelle_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Claw",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins claw.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Basalt Pillar",
        bossImg: "images/boss/basalt pillar.png",
        boss: "(Geo Hypostasis)"
    },
    ningguang: {
        name: "Ningguang",
        vision: "geo",
        icon: "images/portraits/Ningguang_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Spirit Locket of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/spirit locket of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Basalt Pillar",
        bossImg: "images/boss/basalt pillar.png",
        boss: "(Geo Hypostasis)"
    },
    zhongli: {
        name: "Zhongli",
        vision: "geo",
        icon: "images/portraits/Zhongli_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Tusk of Monoceros Caeli",
        weeklyImg: [GenerateTalentImage("images/weekly/tusk of monoceros caeli.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Basalt Pillar",
        bossImg: "images/boss/basalt pillar.png",
        boss: "(Geo Hypostasis)"
    },
    bennett: {
        name: "Bennett",
        vision: "pyro",
        icon: "images/portraits/Bennett_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Plume",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins plume.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    diluc: {
        name: "Diluc",
        vision: "pyro",
        icon: "images/portraits/Diluc_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Plume",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins plume.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    klee: {
        name: "Klee",
        vision: "pyro",
        icon: "images/portraits/Klee_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Ring of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/ring of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    xiangling: {
        name: "Xiangling",
        vision: "pyro",
        icon: "images/portraits/Xiangling_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Dvalin's Claw",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins claw.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    xinyan: {
        name: "Xinyan",
        vision: "pyro",
        icon: "images/portraits/Xinyan_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Tusk of Monoceros Caeli",
        weeklyImg: [GenerateTalentImage("images/weekly/tusk of monoceros caeli.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Everflame Seed",
        bossImg: "images/boss/everflame seed.png",
        boss: "(Pyro Regisvine)"
    },
    tartaglia: {
        name: "Tartaglia",
        vision: "hydro",
        icon: "images/portraits/Tartaglia_Icon.png",
        talent: "Freedom",
        talentImg: [GenerateTalentImage("images/talents/freedom.png")],
        days: "(Mon/Thur)",
        weekly: "Shard of a Foul Legacy",
        weeklyImg: [GenerateTalentImage("images/weekly/shard of a foul legacy.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Cleansing Heart",
        bossImg: "images/boss/cleansing heart.png",
        boss: "(Oceanid)"
    },
    mona: {
        name: "Mona",
        vision: "hydro",
        icon: "images/portraits/Mona_Icon.png",
        talent: "Resistance",
        talentImg: [GenerateTalentImage("images/talents/resistance.png")],
        days: "(Tue/Fri)",
        weekly: "Ring of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/ring of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Cleansing Heart",
        bossImg: "images/boss/cleansing heart.png",
        boss: "(Oceanid)"
    },
    xingqiu: {
        name: "Xingqiu",
        vision: "hydro",
        icon: "images/portraits/Xingqiu_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Tail of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/tail of boreas.png")],
        weeklyBoss: "(Andrius Wolf of the North)",
        bossMat: "Cleansing Heart",
        bossImg: "images/boss/cleansing heart.png",
        boss: "(Oceanid)"
    },
    yanfei: {
        name: "Yanfei",
        vision: "pyro",
        icon: "images/portraits/Yanfei_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Bloodjade Branch",
        weeklyImg: [GenerateTalentImage("images/weekly/bloodjade branch.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Juvenile Jade",
        bossImg: "images/boss/juvenile jade.png",
        boss: "(Primo Geovishap)"
    },
    hutao: {
        name: "Hu Tao",
        vision: "pyro",
        icon: "images/portraits/Hu_Tao_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Shard of a Foul Legacy",
        weeklyImg: [GenerateTalentImage("images/weekly/shard of a foul legacy.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Juvenile Jade",
        bossImg: "images/boss/juvenile jade.png",
        boss: "(Primo Geovishap)"
    },
    xiao: {
        name: "Xiao",
        vision: "anemo",
        icon: "images/portraits/Xiao_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Shadow of the Warrior",
        weeklyImg: [GenerateTalentImage("images/weekly/shadow of the warrior.png")],
        weeklyBoss: "(Childe)",
        bossMat: "Juvenile Jade",
        bossImg: "images/boss/juvenile jade.png",
        boss: "(Primo Geovishap)"
    },
    kaedeharaKazuha: {
        name: "Kaedehara Kazuha",
        vision: "anemo",
        icon: "images/portraits/Kaedehara_Kazuha_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Gilded Scale",
        weeklyImg: [GenerateTalentImage("images/weekly/gilded scale.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Marionette Core",
        bossImg: "images/boss/marionette core.png",
        boss: "(Maguu Kenki)"
    },
    sayu: {
        name: "Sayu",
        vision: "anemo",
        icon: "images/portraits/Sayu_Icon.png",
        talent: "Light",
        talentImg: [GenerateTalentImage("images/talents/light.png")],
        days: "(Wed/Sat)",
        weekly: "Gilded Scale",
        weeklyImg: [GenerateTalentImage("images/weekly/gilded scale.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Marionette Core",
        bossImg: "images/boss/marionette core.png",
        boss: "(Maguu Kenki)"
    },
    gorou: {
        name: "Gorou",
        vision: "geo",
        icon: "images/portraits/Gorou_Icon.png",
        talent: "Light",
        talentImg: [GenerateTalentImage("images/talents/light.png")],
        days: "(Wed/Sat)",
        weekly: "Molten Moment",
        weeklyImg: [GenerateTalentImage("images/weekly/molten moment.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Perpetual Heart",
        bossImg: "images/boss/perpetual heart.png",
        boss: "(Perpetual Mechanic Array)"
    },
    kamisatoAyaka: {
        name: "Kamisato Ayaka",
        vision: "cryo",
        icon: "images/portraits/Kamisato_Ayaka_Icon.png",
        talent: "Elegance",
        talentImg: [GenerateTalentImage("images/talents/elegance.png")],
        days: "(Tue/Fri)",
        weekly: "Bloodjade Branch",
        weeklyImg: [GenerateTalentImage("images/weekly/bloodjade branch.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Perpetual Heart",
        bossImg: "images/boss/perpetual heart.png",
        boss: "(Perpetual Mechanic Array)"
    },
    thoma: {
        name: "Thoma",
        vision: "pyro",
        icon: "images/portraits/Thoma_Icon.png",
        talent: "Transience",
        talentImg: [GenerateTalentImage("images/talents/transience.png")],
        days: "(Mon/Thur)",
        weekly: "Hellfire Butterfly",
        weeklyImg: [GenerateTalentImage("images/weekly/hellfire butterfly.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Smoldering Pearl",
        bossImg: "images/boss/smoldering pearl.png",
        boss: "(Pyro Hypostasis)"
    },
    yoimiya: {
        name: "Yoimiya",
        vision: "pyro",
        icon: "images/portraits/Yoimiya_Icon.png",
        talent: "Transience",
        talentImg: [GenerateTalentImage("images/talents/transience.png")],
        days: "(Mon/Thur)",
        weekly: "Dragon Lord's Crown",
        weeklyImg: [GenerateTalentImage("images/weekly/dragon lords crown.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Smoldering Pearl",
        bossImg: "images/boss/smoldering pearl.png",
        boss: "(Pyro Hypostasis)"
    },
    sangonomiyaKokomi: {
        name: "Sangonomiya Kokomi",
        vision: "hydro",
        icon: "images/portraits/Sangonomiya_Kokomi_Icon.png",
        talent: "Transience",
        talentImg: [GenerateTalentImage("images/talents/transience.png")],
        days: "(Mon/Thur)",
        weekly: "Hellfire Butterfly",
        weeklyImg: [GenerateTalentImage("images/weekly/hellfire butterfly.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Dew of Repudiation",
        bossImg: "images/boss/dew of repudiation.png",
        boss: "(Hydro Hypostasis)"
    },
    kamisatoAyato: {
        name: "Kamisato Ayato",
        vision: "hydro",
        icon: "images/portraits/Kamisato_Ayato_Icon.png",
        talent: "Elegance",
        talentImg: [GenerateTalentImage("images/talents/elegance.png")],
        days: "(Tue/Fri)",
        weekly: "Mudra of the Malefic General",
        weeklyImg: [GenerateTalentImage("images/weekly/mudra of the malefic general.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Dew of Repudiation",
        bossImg: "images/boss/dew of repudiation.png",
        boss: "(Hydro Hypostasis)"
    },
    kujouSara: {
        name: "Kujou Sara",
        vision: "electro",
        icon: "images/portraits/Kujou_Sara_Icon.png",
        talent: "Elegance",
        talentImg: [GenerateTalentImage("images/talents/elegance.png")],
        days: "(Tue/Fri)",
        weekly: "Ashen Heart",
        weeklyImg: [GenerateTalentImage("images/weekly/ashen heart.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Storm Beads",
        bossImg: "images/boss/storm beads.png",
        boss: "(Thunder Manifestation)"
    },
    raidenEi: {
        name: "Raiden Ei",
        vision: "electro",
        icon: "images/portraits/Raiden_Shogun_Icon.png",
        talent: "Light",
        talentImg: [GenerateTalentImage("images/talents/light.png")],
        days: "(Wed/Sat)",
        weekly: "Molten Moment",
        weeklyImg: [GenerateTalentImage("images/weekly/molten moment.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Storm Beads",
        bossImg: "images/boss/storm beads.png",
        boss: "(Thunder Manifestation)"
    },
    aratakiItto: {
        name: "Arataki Itto",
        vision: "geo",
        icon: "images/portraits/Arataki_Itto_Icon.png",
        talent: "Elegance",
        talentImg: [GenerateTalentImage("images/talents/elegance.png")],
        days: "(Tue/Fri)",
        weekly: "Molten Moment",
        weeklyImg: [GenerateTalentImage("images/weekly/molten moment.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Riftborn Regalia",
        bossImg: "images/boss/riftborn regalia.png",
        boss: "(Golden Wolflord)"
    },
    yunjin: {
        name: "Yun Jin",
        vision: "geo",
        icon: "images/portraits/Yun_Jin_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Ashen Heart",
        weeklyImg: [GenerateTalentImage("images/weekly/ashen heart.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Riftborn Regalia",
        bossImg: "images/boss/riftborn regalia.png",
        boss: "(Golden Wolflord)"
    },
    cyno: {
        name: "Cyno",
        vision: "electro",
        icon: "images/portraits/Cyno_Icon.png",
        talent: "Admonition",
        talentImg: [GenerateTalentImage("images/talents/admonition.png")],
        days: "(Mon/Thur)",
        weekly: "Mudra of the Malefic General",
        weeklyImg: [GenerateTalentImage("images/weekly/mudra of the malefic general.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Thunderclap Fruitcore",
        bossImg: "images/boss/thunderclap fruitcore.png",
        boss: "(Electro Regisvine)"
    },
    dori: {
        name: "Dori",
        vision: "electro",
        icon: "images/portraits/Dori_Icon.png",
        talent: "Ingenuity",
        talentImg: [GenerateTalentImage("images/talents/ingenuity.png")],
        days: "(Tue/Fri)",
        weekly: "Bloodjade Branch",
        weeklyImg: [GenerateTalentImage("images/weekly/bloodjade branch.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Thunderclap Fruitcore",
        bossImg: "images/boss/thunderclap fruitcore.png",
        boss: "(Electro Regisvine)"
    },
    layla: {
        name: "Layla",
        vision: "cryo",
        icon: "images/portraits/Layla_Icon.png",
        talent: "Ingenuity",
        talentImg: [GenerateTalentImage("images/talents/ingenuity.png")],
        days: "(Tue/Fri)",
        weekly: "Mirror of Mushin",
        weeklyImg: [GenerateTalentImage("images/weekly/mirror of mushin.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Perpetual Caliber",
        bossImg: "images/boss/perpetual caliber.png",
        boss: "(Aeonblight Drake)"
    },
    wanderer: {
        name: "Wanderer",
        vision: "anemo",
        icon: "images/portraits/Wanderer_Icon.png",
        talent: "Praxis",
        talentImg: [GenerateTalentImage("images/talents/praxis.png")],
        days: "(Wed/Sat)",
        weekly: "Daka's Bell",
        weeklyImg: [GenerateTalentImage("images/weekly/dakas bell.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Perpetual Caliber",
        bossImg: "images/boss/perpetual caliber.png",
        boss: "(Aeonblight Drake)"
    },
    nilou: {
        name: "Nilou",
        vision: "hydro",
        icon: "images/portraits/Nilou_Icon.png",
        talent: "Praxis",
        talentImg: [GenerateTalentImage("images/talents/praxis.png")],
        days: "(Wed/Sat)",
        weekly: "Tears of the Calamitous God",
        weeklyImg: [GenerateTalentImage("images/weekly/tears of the calamitous god.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Perpetual Caliber",
        bossImg: "images/boss/perpetual caliber.png",
        boss: "(Aeonblight Drake)"
    },
    candace: {
        name: "Candace",
        vision: "hydro",
        icon: "images/portraits/Candace_Icon.png",
        talent: "Admonition",
        talentImg: [GenerateTalentImage("images/talents/admonition.png")],
        days: "(Mon/Thur)",
        weekly: "Tears of the Calamitous God",
        weeklyImg: [GenerateTalentImage("images/weekly/tears of the calamitous god.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Light Guiding Tetrahedron",
        bossImg: "images/boss/light guiding tetrahedron.png",
        boss: "(ASIMON)"
    },
    dehya: {
        name: "Dehya",
        vision: "pyro",
        icon: "images/portraits/Dehya_Icon.png",
        talent: "Praxis",
        talentImg: [GenerateTalentImage("images/talents/praxis.png")],
        days: "(Wed/Sat)",
        weekly: "Puppet Strings",
        weeklyImg: [GenerateTalentImage("images/weekly/puppet strings.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Light Guiding Tetrahedron",
        bossImg: "images/boss/light guiding tetrahedron.png",
        boss: "(ASIMON)"
    },
    faruzan: {
        name: "Faruzan",
        vision: "anemo",
        icon: "images/portraits/Faruzan_Icon.png",
        talent: "Admonition",
        talentImg: [GenerateTalentImage("images/talents/admonition.png")],
        days: "(Mon/Thur)",
        weekly: "Puppet Strings",
        weeklyImg: [GenerateTalentImage("images/weekly/puppet strings.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Light Guiding Tetrahedron",
        bossImg: "images/boss/light guiding tetrahedron.png",
        boss: "(ASIMON)"
    },
    kaveh: {
        name: "Kaveh",
        vision: "dendro",
        icon: "images/portraits/Kaveh_Icon.png",
        talent: "Ingenuity",
        talentImg: [GenerateTalentImage("images/talents/ingenuity.png")],
        days: "(Tue/Fri)",
        weekly: "Primordial Greenbloom",
        weeklyImg: [GenerateTalentImage("images/weekly/primordial greenbloom.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Quelled Creeper",
        bossImg: "images/boss/quelled creeper.png",
        boss: "(Dendro Hypostasis)"
    },
    nahida: {
        name: "Nahida",
        vision: "dendro",
        icon: "images/portraits/Nahida_Icon.png",
        talent: "Ingenuity",
        talentImg: [GenerateTalentImage("images/talents/ingenuity.png")],
        days: "(Tue/Fri)",
        weekly: "Puppet Strings",
        weeklyImg: [GenerateTalentImage("images/weekly/puppet strings.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Quelled Creeper",
        bossImg: "images/boss/quelled creeper.png",
        boss: "(Dendro Hypostasis)"
    },
    yaoyao: {
        name: "Yaoyao",
        vision: "dendro",
        icon: "images/portraits/Yaoyao_Icon.png",
        talent: "Diligence",
        talentImg: [GenerateTalentImage("images/talents/diligence.png")],
        days: "(Tue/Fri)",
        weekly: "Daka's Bell",
        weeklyImg: [GenerateTalentImage("images/weekly/dakas bell.png")],
        weeklyBoss: "(Scaramouche)",
        bossMat: "Quelled Creeper",
        bossImg: "images/boss/quelled creeper.png",
        boss: "(Dendro Hypostasis)"
    },
    mika: {
        name: "Mika",
        vision: "cryo",
        icon: "images/portraits/Mika_Icon.png",
        talent: "Ballad",
        talentImg: [GenerateTalentImage("images/talents/ballad.png")],
        days: "(Wed/Sat)",
        weekly: "Mirror of Mushin",
        weeklyImg: [GenerateTalentImage("images/weekly/mirror of mushin.png")],
        weeklyBoss: "(Everlasting Lord of Arcane Wisdom)",
        bossMat: "Pseudo-Stamens",
        bossImg: "images/boss/pseudo stamen.png",
        boss: "(Setekh Wenut)"
    },
    baizhu: {
        name: "Baizhu",
        vision: "dendro",
        icon: "images/portraits/Baizhu_Icon.png",
        talent: "Gold",
        talentImg: [GenerateTalentImage("images/talents/gold.png")],
        days: "(Wed/Sat)",
        weekly: "Worldspan Fern",
        weeklyImg: [GenerateTalentImage("images/weekly/worldspan fern.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Evergloom Ring",
        bossImg: "images/boss/evergloom ring.png",
        boss: "(Inquitous Baptist)"
    },
    kirara: {
        name: "Kirara",
        vision: "dendro",
        icon: "images/portraits/Kirara_Icon.png",
        talent: "Transience",
        talentImg: [GenerateTalentImage("images/talents/transience.png")],
        days: "(Mon/Thur)",
        weekly: "Everamber",
        weeklyImg: [GenerateTalentImage("images/weekly/everamber.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Evergloom Ring",
        bossImg: "images/boss/evergloom ring.png",
        boss: "(Inquitous Baptist)"
    },
    lynette: {
        name: "Lynette",
        vision: "anemo",
        icon: "images/portraits/Lynette_Icon.png",
        talent: "Order",
        talentImg: [GenerateTalentImage("images/talents/order.png")],
        days: "(Wed/Sat)",
        weekly: "Everamber",
        weeklyImg: [GenerateTalentImage("images/weekly/everamber.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Artificed Spare Clockwork Component - Coppelia",
        bossImg: "images/boss/spare clockwork component coppelia.png",
        boss: "(Icewind Suite: Dirge of Coppelia)"
    },
    freminet: {
        name: "Freminet",
        vision: "cryo",
        icon: "images/portraits/Freminet_Icon.png",
        talent: "Justice",
        talentImg: [GenerateTalentImage("images/talents/justice.png")],
        days: "(Tue/Fri)",
        weekly: "Worldspan Fern",
        weeklyImg: [GenerateTalentImage("images/weekly/worldspan fern.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Artificed Spare Clockwork Component - Coppelius",
        bossImg: "images/boss/spare clockwork component coppelius.png",
        boss: "(Icewind Suite: Dirge of Coppelius)"
    },
    navia: {
        name: "Navia",
        vision: "geo",
        icon: "images/portraits/Navia_Icon.png",
        talent: "Equity",
        talentImg: [GenerateTalentImage("images/talents/equity.png")],
        days: "(Mon/Thur)",
        weekly: "Lightless Silk String",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless silk string.png")],
        weeklyBoss: "(All-Devouring Narwhal)",
        bossMat: "Artificed Spare Clockwork Component - Coppelius",
        bossImg: "images/boss/spare clockwork component coppelius.png",
        boss: "(Icewind Suite: Dirge of Coppelius)"
    },
    lyney: {
        name: "Lyney",
        vision: "pyro",
        icon: "images/portraits/Lyney_Icon.png",
        talent: "Equity",
        talentImg: [GenerateTalentImage("images/talents/equity.png")],
        days: "(Mon/Thur)",
        weekly: "Primordial Greenbloom",
        weeklyImg: [GenerateTalentImage("images/weekly/primordial greenbloom.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Emperor's Resolution",
        bossImg: "images/boss/emperors resolution.png",
        boss: "(Emperor of Fire and Iron)"
    },
    gaming: {
        name: "Gaming",
        vision: "pyro",
        icon: "images/portraits/Gaming_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Lightless Mass",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless mass.png")],
        weeklyBoss: "(All Devouring Narwhal)",
        bossMat: "Emperor's Resolution",
        bossImg: "images/boss/emperors resolution.png",
        boss: "(Emperor of Fire and Iron)"
    },
    collei: {
        name: "Collei",
        vision: "dendro",
        icon: "images/portraits/Collei_Icon.png",
        talent: "Praxis",
        talentImg: [GenerateTalentImage("images/talents/praxis.png")],
        days: "(Wed/Sat)",
        weekly: "Tears of the Calamitous God",
        weeklyImg: [GenerateTalentImage("images/weekly/tears of the calamitous god.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Majestic Hooded Beak",
        bossImg: "images/boss/majestic hooked beak.png",
        boss: "(Jadeplume Terrorshroom)"
    },
    tighnari: {
        name: "Tighnari",
        vision: "dendro",
        icon: "images/portraits/Tighnari_Icon.png",
        talent: "Admonition",
        talentImg: [GenerateTalentImage("images/talents/admonition.png")],
        days: "(Mon/Thur)",
        weekly: "The Meaning of Aeons",
        weeklyImg: [GenerateTalentImage("images/weekly/the meaning of aeons.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Majestic Hooded Beak",
        bossImg: "images/boss/majestic hooked beak.png",
        boss: "(Jadeplume Terrorshroom)"
    },
    shenhe: {
        name: "Shenhe",
        vision: "cyro",
        icon: "images/portraits/Shenhe_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Hellfire Butterfly",
        weeklyImg: [GenerateTalentImage("images/weekly/hellfire butterfly.png")],
        weeklyBoss: "(La Signora)",
        bossMat: "Dragonheir's False Fin",
        bossImg: "images/boss/dragonheir false fin.png",
        boss: "(Bathysmal Vishap)"
    },
    yaeMiko: {
        name: "Yae Miko",
        vision: "electro",
        icon: "images/portraits/Yae_Miko_Icon.png",
        talent: "Light",
        talentImg: [GenerateTalentImage("images/talents/light.png")],
        days: "(Wed/Sat)",
        weekly: "The Meaning of Aeons",
        weeklyImg: [GenerateTalentImage("images/weekly/the meaning of aeons.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Dragonheir's False Fin",
        bossImg: "images/boss/dragonheir false fin.png",
        boss: "(Bathysmal Vishap)"
    },
    kukiShinobu: {
        name: "Kuki Shinobu",
        vision: "electro",
        icon: "images/portraits/Kuki_Shinobu_Icon.png",
        talent: "Elegance",
        talentImg: [GenerateTalentImage("images/talents/elegance.png")],
        days: "(Tue/Fri)",
        weekly: "Tears of the Calamitous God",
        weeklyImg: [GenerateTalentImage("images/weekly/tears of the calamitous god.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Runic Fang",
        bossImg: "images/boss/runic fang.png",
        boss: "(Ruin Serpent)"
    },
    yelan: {
        name: "Yelan",
        vision: "hydro",
        icon: "images/portraits/Yelan_Icon.png",
        talent: "Prosperity",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png")],
        days: "(Mon/Thur)",
        weekly: "Gilded Scale",
        weeklyImg: [GenerateTalentImage("images/weekly/gilded scale.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Runic Fang",
        bossImg: "images/boss/runic fang.png",
        boss: "(Ruin Serpent)"
    },
    shikanoinHeizou: {
        name: "Shikanoin Heizou",
        vision: "anemo",
        icon: "images/portraits/Shikanoin_Heizou_Icon.png",
        talent: "Transience",
        talentImg: [GenerateTalentImage("images/talents/transience.png")],
        days: "(Mon/Thur)",
        weekly: "The Meaning of Aeons",
        weeklyImg: [GenerateTalentImage("images/weekly/the meaning of aeons.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Runic Fang",
        bossImg: "images/boss/runic fang.png",
        boss: "(Ruin Serpent)"
    },
    chevreuse: {
        name: "Chevreuse",
        vision: "pyro",
        icon: "images/portraits/Chevreuse_Icon.png",
        talent: "Order",
        talentImg: [GenerateTalentImage("images/talents/order.png")],
        days: "(Wed/Sat)",
        weekly: "Lightless Eye of the Maelstrom",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless eye of the maelstrom.png")],
        weeklyBoss: "(All Devouring Narwhal)",
        bossMat: "Fontemer Unihorn",
        bossImg: "images/boss/fontemer unihorn.png",
        boss: "(Millenial Pearl Seahorse)"
    },
    neuvillette: {
        name: "Neuvillette",
        vision: "hydro",
        icon: "images/portraits/Neuvillette_Icon.png",
        talent: "Order",
        talentImg: [GenerateTalentImage("images/talents/order.png")],
        days: "(Wed/Sat)",
        weekly: "Everamber",
        weeklyImg: [GenerateTalentImage("images/weekly/everamber.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Fontemer Unihorn",
        bossImg: "images/boss/fontemer unihorn.png",
        boss: "(Millenial Pearl Seahorse)"
    },
    wriothesley: {
        name: "Wriothesley",
        vision: "cryo",
        icon: "images/portraits/Wriothesley_Icon.png",
        talent: "Order",
        talentImg: [GenerateTalentImage("images/talents/order.png")],
        days: "(Wed/Sat)",
        weekly: "Primordial Greenbloom",
        weeklyImg: [GenerateTalentImage("images/weekly/primordial greenbloom.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Tourbillon Device",
        bossImg: "images/boss/tourbillon.png",
        boss: "(Prototype Cal. Breguet)"
    },
    charlotte: {
        name: "Charlotte",
        vision: "cryo",
        icon: "images/portraits/Charlotte_Icon.png",
        talent: "Justice",
        talentImg: [GenerateTalentImage("images/talents/justice.png")],
        days: "(Tue/Fri)",
        weekly: "Lightless Silk String",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless silk string.png")],
        weeklyBoss: "(All Devouring Narwhal)",
        bossMat: "Tourbillon Device",
        bossImg: "images/boss/tourbillon.png",
        boss: "(Prototype Cal. Breguet)"
    },
    furina: {
        name: "Furina",
        vision: "hydro",
        icon: "images/portraits/Furina_Icon.png",
        talent: "Justice",
        talentImg: [GenerateTalentImage("images/talents/justice.png")],
        days: "(Tue/Fri)",
        weekly: "Lightless Mass",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless mass.png")],
        weeklyBoss: "(All Devouring Narwhal)",
        bossMat: "Water That Failed to Transcend",
        bossImg: "images/boss/water that failed to transcend.png",
        boss: "(Hydro Tulpa)"
    },
    xianyun: {
        name: "Xianyun",
        vision: "anemo",
        icon: "images/portraits/Xianyun_Icon.png",
        talent: "Order",
        talentImg: [GenerateTalentImage("images/talents/order.png")],
        days: "(Wed/Sat)",
        weekly: "Lightless Eye of the Maelstrom",
        weeklyImg: [GenerateTalentImage("images/weekly/lightless eye of the maelstrom.png")],
        weeklyBoss: "(All Devouring Narwhal)",
        bossMat: "Cloudseam Scale",
        bossImg: "images/boss/cloudseam scale.png",
        boss: "(Solitary Suanni)"
    },
    travelerAnemo: {
        name: "Traveler (Anemo)",
        vision: "anemo",
        icon: "images/portraits/Traveler_Icon.png",
        talent: "Freedom, Resistance, Ballad",
        talentImg: [GenerateTalentImage("images/talents/freedom.png"), GenerateTalentImage("images/talents/resistance.png"), GenerateTalentImage("images/talents/ballad.png")],
        days: "",
        weekly: "Dvalin's Sigh",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png")],
        weeklyBoss: "(Stormterror)",
        bossMat: "Brilliant Diamond Gemstone",
        bossImg: "images/boss/brilliant gemstone.png",
        boss: "(AR rewards)"
    },
    travelerElectro: {
        name: "Traveler (Electro)",
        vision: "electro",
        icon: "images/portraits/Traveler_Icon.png",
        talent: "Transience, Elegance, Light",
        talentImg: [GenerateTalentImage("images/talents/transience.png"), GenerateTalentImage("images/talents/elegance.png"), GenerateTalentImage("images/talents/light.png")],
        days: "",
        weekly: "Dragon Lord's Crown",
        weeklyImg: [GenerateTalentImage("images/weekly/dragon lords crown.png")],
        weeklyBoss: "(Azhdaha)",
        bossMat: "Brilliant Diamond Gemstone",
        bossImg: "images/boss/brilliant gemstone.png",
        boss: "(AR rewards)"
    },
    travelerGeo: {
        name: "Traveler (Geo)",
        vision: "geo",
        icon: "images/portraits/Traveler_Icon.png",
        talent: "Prosperity, Diligence, Gold",
        talentImg: [GenerateTalentImage("images/talents/prosperity.png"), GenerateTalentImage("images/talents/diligence.png"), GenerateTalentImage("images/talents/gold.png")],
        days: "",
        weekly: "Dvalin's Sigh, Tail of Boreas",
        weeklyImg: [GenerateTalentImage("images/weekly/dvalins sigh.png"), GenerateTalentImage("images/weekly/tail of boreas.png")],
        weeklyBoss: "(Stormterror, Andrius Wolf of the North)",
        bossMat: "Brilliant Diamond Gemstone",
        bossImg: "images/boss/brilliant gemstone.png",
        boss: "(AR rewards)"
    },
    travelerDendro: {
        name: "Traveler (Dendro)",
        vision: "dendro",
        icon: "images/portraits/Traveler_Icon.png",
        talent: "Admonition, Ingenuity, Praxis",
        talentImg: [GenerateTalentImage("images/talents/admonition.png"), GenerateTalentImage("images/talents/ingenuity.png"), GenerateTalentImage("images/talents/praxis.png")],
        days: "",
        weekly: "Mudra of the Malefic General",
        weeklyImg: [GenerateTalentImage("images/weekly/mudra of the malefic general.png")],
        weeklyBoss: "(Raiden Shogun)",
        bossMat: "Brilliant Diamond Gemstone",
        bossImg: "images/boss/brilliant gemstone.png",
        boss: "(AR rewards)"
    },
    travelerHydro: {
        name: "Traveler (Hydro)",
        vision: "hydro",
        icon: "images/portraits/Traveler_Icon.png",
        talent: "Equity, Justice, Order",
        talentImg: [GenerateTalentImage("images/talents/equity.png"), GenerateTalentImage("images/talents/justice.png"), GenerateTalentImage("images/talents/order.png")],
        days: "",
        weekly: "Worldspan Fern",
        weeklyImg: [GenerateTalentImage("images/weekly/worldspan fern.png")],
        weeklyBoss: "(Guardian of Apep's Oasis)",
        bossMat: "Brilliant Diamond Gemstone",
        bossImg: "images/boss/brilliant gemstone.png",
        boss: "(AR rewards)"
    }
};

function GenerateTalentImage(src) {
    const img = new Image();
    img.src = src;
    return img;
};